<?php
// =============================================================
// Build render.env — the environment for the deployed backend.
// =============================================================
//   /opt/lampp/bin/php scripts/make-render-env.php
//
// Writes render.env (gitignored) next to env.yaml. Values that are the same
// everywhere — Pesapal, Brevo, the Firebase project, the Google client id —
// are copied across. Values that differ per deployment are left blank with a
// note, because copying them would be wrong:
//
//   DB_HOST/DB_USER/DB_PASS  local env.yaml points at XAMPP, not Cloud SQL
//   DB_SSL_CA                a PEM that only exists in the Cloud SQL console
//   PESAPAL_PUBLIC_BASE_URL  the service's own URL, unknown until it exists
//
// This file deliberately does NOT touch env.yaml. Putting the Cloud SQL host
// in there would silently repoint local development at the production
// database — the sort of mistake that is only noticed after a write.
// =============================================================

require_once __DIR__ . '/../includes/env.php';

$out = dirname(__DIR__) . '/render.env';
if (file_exists($out) && !in_array('--force', $argv, true)) {
    fwrite(STDERR, "render.env already exists. Re-run with --force to overwrite.\n");
    exit(1);
}

// [key, value, comment]. A null value means "you must fill this in".
$copied = fn($k, $default = '') => env($k, $default);

$rows = [
    ['# --- Storage -------------------------------------------------', null, null],
    ['GCS_BUCKET', 'afamfresh-uploads', null],

    ['# --- Database: Cloud SQL over TCP ----------------------------', null, null],
    ['DB_HOST', null, 'Cloud SQL public IP (Overview -> Connect to this instance)'],
    ['DB_PORT', '3306', null],
    ['DB_NAME', 'kitchen', null],
    ['DB_USER', null, 'NOT root in production — create a dedicated user'],
    ['DB_PASS', null, 'that user\'s password'],
    ['DB_SSL_CA', null, 'PEM from Connections -> Security -> server CA. Paste in the Render UI, not here: it is multi-line.'],

    ['# --- Firebase: push notifications and bucket uploads ---------', null, null],
    ['FIREBASE_PROJECT_ID', $copied('FIREBASE_PROJECT_ID', 'afamfresh-f68c6'), null],
    ['FIREBASE_CREDENTIALS_JSON', null, 'whole service-account.json on one line — see the note printed below'],

    ['# --- Google Sign-In ------------------------------------------', null, null],
    ['GOOGLE_WEB_CLIENT_ID', $copied('GOOGLE_WEB_CLIENT_ID'), null],

    ['# --- Payments -------------------------------------------------', null, null],
    ['PESAPAL_ENV', $copied('PESAPAL_ENV', 'live'), null],
    ['PESAPAL_CONSUMER_KEY', $copied('PESAPAL_CONSUMER_KEY'), null],
    ['PESAPAL_CONSUMER_SECRET', $copied('PESAPAL_CONSUMER_SECRET'), null],
    ['PESAPAL_IPN_ID', $copied('PESAPAL_IPN_ID'), 're-register against the deployed URL once it exists'],
    ['PESAPAL_PUBLIC_BASE_URL', null, 'the service\'s own https URL, once Render assigns it'],

    ['# --- Email ----------------------------------------------------', null, null],
    ['BREVO_API_KEY', $copied('BREVO_API_KEY'), null],
];

$lines = [
    '# Generated by scripts/make-render-env.php — do not commit.',
    '# Paste into Render: service -> Environment -> Add from .env',
    '',
];
$missing = [];
foreach ($rows as [$k, $v, $note]) {
    if (str_starts_with($k, '#')) { $lines[] = ''; $lines[] = $k; continue; }
    if ($note) $lines[] = "# $note";
    if ($v === null || $v === '') { $missing[] = $k; $lines[] = "$k="; }
    else                          { $lines[] = "$k=$v"; }
}

file_put_contents($out, implode("\n", $lines) . "\n");
chmod($out, 0600);

echo "wrote $out (chmod 600, gitignored)\n\n";
echo "Copied from env.yaml: " . (count($rows) - count($missing) - 7) . " values\n";
echo "You must fill in " . count($missing) . ":\n";
foreach ($missing as $m) echo "  - $m\n";

echo "\nFor FIREBASE_CREDENTIALS_JSON, flatten the key to one line with:\n";
echo "  php -r 'echo json_encode(json_decode(file_get_contents(\"storage/firebase/service-account.json\")));'\n";
echo "\nDB_SSL_CA is multi-line; paste it directly into Render's env var editor.\n";
